name: pbl_if14
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  network_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash1.png
    - assets\images\bg1.png
    - assets\images\megamall.png
    - assets\images\jembatan1.jpeg
    - assets\images\beach.jpg
    - assets\images\shopping.jpg
    - assets\images\amusement_park.jpg
    - assets\images\wtb.jpg
    - assets\images\vio-vio.jpg
    - assets\images\location.png
    - assets\images\Detail.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/static/Montserrat-Regular.ttf
        - asset: assets/fonts/static/Montserrat-Bold.ttf

flutter_native_splash:
  image: assets/splash.png
  color: "#42a5f5"
  android: true
  ios: true
